### ISSUE TITLE
Emitted warnings that should not be (since `0.51.0`)

### ISSUE THREAD

**Issue by BrokenSourceCode** [apidoc/apidoc#1194]
# Describe the bug

With the version `0.51.0`, apidoc [emits warnings if there are inconsistencies in the parameters](https://github.com/apidoc/apidoc/pull/1189), but these warnings are also emitted when parameters are present into the query string.

I isolated the origin of the issue here: https://github.com/apidoc/apidoc/blob/a18fd1ee35c540ff171314bf99d393279143a063/lib/core/parser.js#L517-L523

The API parameters are parsed with the URL parts delimited by `/`, but the parse should consider the parts of the query string (e.g. `?foo=:foo&bar=:bar&baz=:baz`.

# Steps to reproduce

`api.js`:
```
/**
 * @api {GET} /my-api?foo=:foo MyApi
 * @apiName MyApi
 * @apiParam {String} foo
 */
```

`logs`:
```log
warn: @apiParam 'foo' was defined but does not appear in URL of @api 'MyApi' in file: 'api.js'
```

# Information

- Version of apidoc: 0.51.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows 10
- Node version: 16.13.2
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
apiBody would be for the body of the request/response whereas apiparam is parameters in the url. Yes please issue a PR and make sure to add test cases ;)

**Comment by BrokenSourceCode** [comment]
> apiBody would be for the body of the request/response whereas apiparam is parameters in the url. Yes please issue a PR and make sure to add test cases ;)

Ok, thanks for your explanation. I've opened [a PR](https://github.com/apidoc/apidoc/pull/1195) to fix it.

**Comment by gnickm** [comment]
Just out of curiosity, why not use `@apiQuery`? It nicely separates URL params from query params in the output. [Here's how it looks rendered](https://developers.grandcare.com/gcmanage-api/apidoc/#api-Group-GetCommunityGroups) and here's how the descriptor looks:

```
    /**
     * @api {get} /community/:id/group  Get groups for community
     *
     * @apiParam {String} id  ID of community to look up
     *
     * @apiQuery {String} [filter]     Filters results to the specified field. See
     *                                 Generalized Filtering section for more details
     * @apiQUery {Boolean} [incStats] Set to 'true' to add stats object to returned groups
     */

```

**Comment by BrokenSourceCode** [comment]
> Just out of curiosity, why not use `@apiQuery`? It nicely separates URL params from query params in the output. [Here's how it looks rendered](https://developers.grandcare.com/gcmanage-api/apidoc/#api-Group-GetCommunityGroups) and here's how the descriptor looks:
> 
> ```
>     /**
>      * @api {get} /community/:id/group  Get groups for community
>      *
>      * @apiParam {String} id  ID of community to look up
>      *
>      * @apiQuery {String} [filter]     Filters results to the specified field. See
>      *                                 Generalized Filtering section for more details
>      * @apiQUery {Boolean} [incStats] Set to 'true' to add stats object to returned groups
>      */
> ```

Thanks, i will try it tomorrow. If it works for me, I'll let @NicolasCARPi decide if the PR is still necessary or not!

**Comment by BrokenSourceCode** [comment]
@gnickm Your solution looks really great! I wasn't aware of the `@apiQuery` tag...It's appropriate for my case. Thanks!

@NicolasCARPi Is there still any reason for this issue to be open? I think not since apidoc provides a `@apiQuery` tag. For the [pull request](https://github.com/apidoc/apidoc/pull/1195) I've published, I would suggest to close it and create a new one to only remove the useless dependencies, but not to correct this issue which is not really a bug.

**Comment by BrokenSourceCode** [comment]
For the closing reason, see https://github.com/apidoc/apidoc/issues/1194#issuecomment-1092795799.

**Comment by Lemmmy** [comment]
I believe this, or a related issue, may still happen if you use groups.

Emits a warning:

```js
/**
 * @api {get} /addresses/:address Get an address
 * @apiParam (URLParameter) {String} address The address.
 */
```

```
warn: URL contains a parameter ':address' that is not documented as @apiParam in @api 'Get an address' in file: 'src/webserver/routes/addresses.ts'
```

Does not emit a warning:

```js
/**
 * @api {get} /addresses/:address Get an address
 * @apiParam {String} address The address.
 */
```

**Comment by BrokenSourceCode** [comment]
@NicolasCARPi Should we reopen the issue?

**Comment by NicolasCARPi** [comment]
Yes, if someone want to make a PR fixing this I would be glad.

**Comment by BrokenSourceCode** [comment]
> Yes, if someone want to make a PR fixing this I would be glad.

I will take a look but I don't promise anything!

**Comment by BrokenSourceCode** [comment]
@NicolasCARPi @Lemmmy PR opened: https://github.com/apidoc/apidoc/pull/1206

**Comment by NicolasCARPi** [comment]
@Lemmmy can you confirm that the branch of @BrokenSourceCode fixes the issue in your hands?

**Comment by Lemmmy** [comment]
Can confirm this fixes the issue on my project. Thank you for the fix @BrokenSourceCode !
